# Datasource
spring:
  datasource.url: jdbc:h2:mem:todolist;DB_CLOSE_ON_EXIT=FALSE
  datasource.username: sa
  datasource.password:
  datasource.driver-class-name: org.h2.Driver

# Hibernate
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

